name = "predictor-league-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "predictor-db"
database_id = "5aab066d-e744-4580-80bb-dfc010d262b0"

[vars]
ADMIN_SECRET_PATH = "batball6464"
ADMIN_PASSWORD    = "dhamaal"
PUBLIC_ORIGIN     = "https://predictor.yourdomain.com"
ADMIN_ORIGIN      = "https://admin.yourdomain.com"

[[triggers]]
crons = ["*/5 * * * *"]
